### ISSUE TITLE
Flickity viewport created after cell elements

### ISSUE THREAD

**Issue by damienroche** [benjamincharity/angular-flickity#34] opened 2016-05-13 21:43 UTC
Hello Benjamin,
I'm trying to use Flickity in my angularjs project.
However, after setting my slider like this
```
<div bc-flickity="{{sliderOptions}}">
	<figure ng-class="'slide background-image'" data-ng-repeat="photo in module.gallerie">
		<img ng-src="{{photo.url}}">
	</figure>
</div>
```

The HTML output is like that : 
![unspecified](https://cloud.githubusercontent.com/assets/270193/15265617/2a8b04e8-1957-11e6-93b4-22240e54ee91.png)

The flickity seems to be instanciate. But the cells aren't in the right place (before the flickity-viewport div)

**Comment by benjamincharity** [comment] 2016-05-14 02:05
Hey @damienroche, that is really odd! I can't seem to replicate that in my test project or a Plunker. Would you mind trying to reproduce in a Plunker so that I can see what is happening? You can fork one of my demos to save some time: http://plnkr.co/edit/qdyKKo?p=preview

**Comment by benjamincharity** [comment] 2016-06-13 12:42
Closing for now due to lack of information / reproducible case. Feel free to reopen with more information!

**Closed by benjamincharity** 2016-06-13 12:42 UTC
Labels: Status: Waiting on Feedback
