### ISSUE TITLE
Contain property is not working.

### ISSUE THREAD

**Issue by MukulSinghKumawat** [benjamincharity/angular-flickity#56] opened 2016-10-04 07:35 UTC
How can i view multiple slides one time.
contain property is not working.

**Comment by benjamincharity** [comment] 2016-10-04 16:36
Hello @MukulSinghKumawat,

I'm not sure I understand what the issue is.  Viewing multiple slides is not related to the contain property.

The contain property simply aligns the first cell to the left to avoid any extra space before the first cell. See the docs: http://flickity.metafizzy.co/options.html#contain

Here is a working demo that shows two sliders; one with `contain: true` and one without `contain` set: http://plnkr.co/edit/A8Ao3P

You can see in the demo that multiple slides are visible at the same time. This is based on your slideshow styles.

---

Closing for now, but if you are still having issues, please create a demo that shows the issue and I will reopen and try to help. (Fork [this demo](http://plnkr.co/edit/A8Ao3P) for a quick starting point)

**Closed** 2016-10-04 16:36 UTC
Labels: Type: Question
