### ISSUE TITLE
Initialize slider "after" loading remote data

### ISSUE THREAD

**Issue by ashishkushwaha** [benjamincharity/angular-flickity#39] opened 2016-06-24 17:26 UTC
Hi @benjamincharity,

Thanks for making this wonderful plugin. I am trying to get the slider work with Remote data (after $http call), but I am facing an issue. 

The wrapper divs (flickity-viewport and flickity-slider) get initialized first and treat the remote data array as an Empty Array. After this, the remote data load get completed and the slides get loaded "before" the wrappers but inside the correct parent.

When i hardcode the Remote Data in the Array directly, everything works. But on including it as a $http call, it fails. I even tried using the service options "after" the $http promise is resolved, but still get the same error.

Is there a way to specify the reload based on some criteria after array is initialized with remote data?

**Comment by ashishkushwaha** [comment] 2016-06-24 17:41
Just to add, the final DOM i am getting is exactly similar to this issue ->   #34

This happens when dealing with Remote Data. The sequence goes like this:

1. Remote request in service
2. DOM already loaded by treating Array as am empty Array. So Flickity viewport gets added diretly inside top level parent.
3. ng-repeat based on remote data initializes (digest cycle) and ng-repeat elements build now (before flickity-viewport, but still inside the root parent).
4. Data shows up on page, but is several block divs followed by empty flickity viewport div.

**Comment by benjamincharity** [comment] 2016-06-24 18:27
Hey there @ashishkushwaha, sorry you're having issues with this! This is definitely a valid issue.

The original Flickity library is purely JavaScript so there is no worry with data not being loaded beforehand (unless you intentionally initialized the slider before your data returned). This issue raises it's head here because I have created a DOM component for the library.

### Solutions

I don't believe I'll be making any changes to the directive itself to support async content. This is for two reasons:

- The original Flickity library doesn't have any type of 'reload' support ([reloadCells](http://flickity.metafizzy.co/api.html#reloadcells) sounds close, but it only re-gathers the elements already inside the Flickity container)
- There are two viable work-arounds for this:
  1. Create the Flickity instance by using the [services](https://github.com/benjamincharity/angular-flickity#services) provided. This will allow you to fetch your data and then, in the callback or promise resolve, you can initialize the Flickity instance once the data is loaded. (Here is a Plunker demo showing the service use: http://plnkr.co/edit/hkT7Tx?p=info)
  1. Add a `data-ng-if="vm.myDataHasLoaded"` flag on the flickity directive. Then, in the callback or promise resolve, you can set that flag to `true`. This would tell Angular to load the directive at that point.

I know neither solution is as easy as setting another directive option, but it would require me to add polling of some type into the library. And since the service can be used to get around this issue I hesitate to do that.

---

Let me know if you are having trouble using either of the workarounds above!

**Comment by ashishkushwaha** [comment] 2016-06-24 18:41
Thanks for the quick reply. I am going to try both the options and get back shortly. Option 2 is something i can try out pretty fast in fact.

**Comment by ashishkushwaha** [comment] 2016-06-24 20:11
Sorry - both options didn't work for me. I have tried promise chaining for both approaches but it always ends up with the same DOM.

For now, I have just applied the dirty approach of adding a hard-coded timeout (i hate it), of 2 seconds while calling the FlickityService.create.

Am not sure why resolving the promise approach is failing though. Issues is not remote data, it first gets the data (then promise is resolved), but the directive and the data still don't render. They render together after some time with directive loading after the ng-repeat, always.

**Comment by benjamincharity** [comment] 2016-06-24 20:41
> Issues is not remote data, it first gets the data (then promise is resolved), but the directive and the data still don't render

To be clear, when creating a Flickity instance with the service, you shouldn't be using the directive. You should be creating the instance and passing in a DOM element. Like this: http://plnkr.co/edit/hkT7Tx?p=info

**Comment by ashishkushwaha** [comment] 2016-06-24 20:47
Yes - in the service approach, I am not using the directive at all. I was using the directive with the ng-if approach (option 2 that you suggested above).

Sorry, I cannot check what needs to be added to the directive, since I am new to angular. But I was using the same approach with slick js carousal with angular slick directive.
https://github.com/devmark/angular-slick-carousel

In their documentation itself, they have the ng-if approach. By setting ng-if as false by default and making it true after the ng-repeat remote data is resolved, that directive works.

But in case of angular flickity, even after the remote data is resolved and ng-if is set to true "after" the promise resolution, the ng-repeat elements are rendered outside the flickity-wrapper div. 

I wish there was a better way for me to explain this.

**Comment by benjamincharity** [comment] 2016-06-24 20:59
No worries.. I will definitely be looking into this tomorrow. The service method should work with remote data. I'll update here when I know more.

Sorry again it's been so tough to get going!

**Comment by ashishkushwaha** [comment] 2016-06-24 21:04
Thanks a lot. No issues. I am also going to investigate this in parallel. This is how I will also learn. Cheers!!!

**Comment by benjamincharity** [comment] 2016-06-26 17:31
Alright, I was able to reproduce some breaking issues when dealing with remote data. It seems that wrapping the `FlickityService.create()` call inside an Angular `$timeout` fixes it. This is just to ensure the data has been bound to scope before `create()` is called.

Here is a Plunker demo using remote data: http://plnkr.co/edit/hkT7Tx?p=preview

I also added a note to the docs to hopefully save others this frustration: https://github.com/benjamincharity/angular-flickity/commit/5e4765d6eef5039d5223c3290f034d7700cfb6e9

Closing for now, but feel free to re-open, or comment if this still isn't working for you.

**Closed by benjamincharity** 2016-06-26 17:31 UTC
Labels: Type: Bug

**Comment by ashishkushwaha** [comment] 2016-06-26 17:53
Thanks a lot. I was using my create within a timeout (with 2000 millisecs hard coded). I will try it without a timeout value too.
